  
backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)

  
publish_mode: editorial_workflow
logo_url: https://beta.equityschool.plus/img/eSchoolPlus.svg
media_folder: 'img'
collections:
  - name: 'team'
    label: 'Team'
    folder: '_team'
    identifier_field: name
    create: true
    editor:
      preview: true
    fields:
      - {label: 'Name', name: 'name', widget: 'string', default: ''}
      - {label: 'Leader', name: 'leader', widget: 'boolean', default: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", media_folder: /img/team, default: "unknown.png"}
      - {label: 'Position', name: 'position', widget: 'text', default: ''}
      - label: "Social Media"
        name: "social"
        widget: "list"
        fields:
          - label: "Icon"
            name: "title"
            widget: "select"
            options: ["user", "linkedin", "twitter"]
            default: ["user"]
          - {label: Url, name: url, widget: string, default: "https://www.jhu.edu/"}

 
      
  - name: 'events'
    label: 'Events'
    folder: '_events'
    identifier_field: title
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'text', default: '', required: true}
      - {label: 'Symbol', name: 'symbol', widget: 'text', default: 'video-camera', required: true}
      - {label: 'Date', name: 'date', widget: 'datetime', default: '', required: true}
      - {label: 'Description', name: 'description', widget: 'text', default: '', required: false, hint: 'A very brief description of your event - synopsis, speakers, etc.'}
      
      
  - name: 'highlights'
    label: 'Highlights'
    folder: '_highlights'
    identifier_field: title
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'text', default: '', required: true}
      - {label: 'Position', name: 'position', widget: 'number', default: '1', value_type: "int", min: 1, max: 21, step: 1} # Max Highlights 21
      - {label: "Featured Image", name: "image", widget: "image", media_folder: /img/highlights, default: "unknown.png"}
      - {label: "Image Alt Text", name: "image-alt-text", widget: 'text', default: '', required: false}
      - {label: 'Description', name: 'description', widget: 'text', default: '', required: false, hint: 'A very brief description of your highlight'}
      - label: "Buttons"
        name: "buttons"
        widget: "list"
        fields:
          - {label: 'Button Label', name: 'label', widget: 'text', default: '', required: false}
          - {label: Link, name: link, widget: string, default: "https://www.jhu.edu/"}

  - name: 'resources'
    label: 'Resources'
    folder: '_resources'
    identifier_field: title
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'text', default: '', required: true}
      - {label: 'Subtitle', name: 'subtitle', widget: 'text', default: '', required: true, hint: 'Small Description of Resource'}
      - {label: "Type", name: "type", widget: 'text', default: '', required: true}
      - {label: 'Link', name: 'link', widget: 'string', default: "https://www.jhu.edu/"}
      - {label: 'Date', name: 'date', widget: 'datetime', date_format: "YYYY-MM-DD", picker_utc: true}
