  
backend:
  name: github
  repo: covideducationrecovery/beta-website
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://aqueous-tor-69024.herokuapp.com
  
publish_mode: editorial_workflow
logo_url: https://beta.covideducationrecovery.global/img/GlobalTracker-2.svg
media_folder: 'img'
collections:
  - name: 'posts'
    label: 'Posts '
    folder: '_posts'
    identifier_field: title
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'text', default: '', required: true}
      - {label: 'Date', name: 'date', widget: 'date', date_format: "MM-DD-YYYY"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", media_folder: /img/posts, default: "unknown.png"}
      - {label: "Image Alt Text", name: "image-alt-text", widget: 'text', default: '', required: false}
      - {label: "Description", name: "description", widget: 'text', required: false, default: 'a collaborative effort of Johns Hopkins University, the World Bank, and UNICEF' ,hint: 'a collaborative effort of Johns Hopkins University, the World Bank, and UNICEF'}
      - { label: 'Media Contacts', name: 'media-contacts', widget: 'markdown' }
      - { label: 'Main Content', name: 'body', widget: 'markdown' }

