name: covid_data_fetch
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"

      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

        
      - name: execute py script # run the run.py to get the latest data
        run: |
          python run.py


      - run: git pull
      - run: git add .
      - run: git commit -m "Added files"
      - run: git push
